### ISSUE TITLE
Can't load shared library libxpcom.so

### ISSUE THREAD

**Issue by rjaduthie** [nextinterfaces/http4e#1]
Hi, I'm attempting to set up a workstation to develop an HTTP REST API with Eclipse.  This plugin looked promising.  However, there seems to be an issue when trying to use the HTTP4e Client.

When attempting to open the HTTP4e view (Window->Show View->[...]->HTTP->HTTP4e Client) an error is generated.  Initially, I got a message:

![http4e_errorno1](https://user-images.githubusercontent.com/343584/27225066-704e3220-5290-11e7-9462-695cab5cb4b9.png)

Then I set MOZILLA_FIVE_HOME to point at "/usr/lib/mozilla" (as per: http://gangmax.me/blog/2012/06/28/mozilla-five-home-error-in-eclipse/).  The error message generated whne trying to open the HTTP4e view changed to:

![http4e_errorno2](https://user-images.githubusercontent.com/343584/27225067-704ee4f4-5290-11e7-9fea-47af2c08c0b1.png)

Details of software:
OS: CentOS7
Eclipse: Indigo Service Release 2 (3.7.2)
Firefox: 52.2.0 (64-bit)
XULRunner: 31.6.0

So, I looked around for this libxpcom.so file, but it's not on my system.  I tried installing the XULRunner package for CentOS7, but this doesn't have the file either.

**Comment by rjaduthie** [comment]
UPDATE: I installed Eclipse Kepler (4.3.2) and now have no problem.

**Comment by paulvi** [comment]
Was it really issue of this plugin? Does it require native binaries?

**Comment by nextinterfaces** [comment]
I couldn't repro the error, it doesn't require native binaries
